server.port=8090
spring.datasource.url=jdbc:mysql://localhost:3306/exporsan_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=${JWT_SECRET:exporsan-ica-secret-jwt-security-key-2026-v1}
jwt.expiration=28800000
