server.port=${PORT:8080}

# Production Database (Aiven)
# spring.datasource.url=jdbc:mysql://mysql-316f14eb-fernandezanderson562-abd7.i.aivencloud.com:18226/defaultdb?useSSL=true&trustServerCertificate=true&allowPublicKeyRetrieval=true
# spring.datasource.username=avnadmin
# spring.datasource.password=AVNS_6G8A4Hw_tRIZDPqG11I

# Local Database (DBeaver / Localhost)
spring.datasource.url=jdbc:mysql://localhost:3306/exporsan_lotes?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Internal service URL routing in monolithic setup
auth.service.url=http://localhost:${PORT:8080}
lote.service.url=http://localhost:${PORT:8080}
calidad.service.url=http://localhost:${PORT:8080}
certificacion.service.url=http://localhost:${PORT:8080}

# JWT Security parameters
jwt.secret=exporsan-ica-secret-jwt-security-key-2026-v1
jwt.expiration=28800000

spring.webservices.path=/ws
spring.jpa.open-in-view=false
spring.security.user.password=none

# External integration (mocks/production)
decolecta.api.url=https://api.decolecta.com/v1
decolecta.api.token=sk_4441.RLFtFN7GuWekyCtN9kemz3SkcP1tOatt

spring.jackson.time-zone=America/Lima
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.serialization.write-dates-as-timestamps=false
