server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/**,/api/v1/usuarios/**
        - id: auditoria-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auditoria/**
        - id: lote-pesca-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/adaptadores/**,/api/v1/maestros/**,/api/v1/consultas/**
        - id: monitoreo-cold-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/calidad/**
        - id: certificacion-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/orch/**,/api/v1/tramites/**,/api/v1/bpm/**
        - id: service-registry
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/registry/**
        - id: soap-embarcaciones
          uri: http://localhost:8081
          predicates:
            - Path=/ws/**

jwt:
  secret: ${JWT_SECRET:exporsan-ica-secret-jwt-security-key-2026-v1}
